name: Automate Data Preprocessing

on:
  push:
    branches:
      - main
    paths:
      - 'dataset_raw/**'
      - 'preprocessing/automate_Jauhan.py'

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas # Tambahkan library lain seperti scikit-learn jika kodemu membutuhkannya

      - name: Run preprocessing script
        run: |
          cd preprocessing
          python automate_Jauhan.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add preprocessing/dataset_preprocessing/
          git commit -m "Auto-update preprocessed data" || echo "No changes to commit"
          git push